language: node_js
node_js:
  - stable
services:
  - mongodb
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: unict
  api_key:
    secure: MFlPz220c0jtZjlBDjLmu9i7NDGpcFMDksPbctDEzVW1sr0JBtWPmKIwS6oycdBjOwOpW+xrdVcDZTluVPXVcwYgfcKCW9RVWfLSoRK2ZkY7UPCm4SNyLe7V78EYBYLK+UEs3u7WNY/s4btyqkB/l8GDR8a3juzpfmzYHl08VZXVmgX3Q8+VTmdZkBmJ5IP8/WdS+fr11b4lkDCObvNn7vXa6ZpPEaRDjsv2MSlUbyOoE7+y3+EnPZPaZPpogYkIVDfY+Rs3hC9GaT60vPXNoOthvCq3vPb+2jw1phTNRw7VBBmmcDtH7Be8/Cj+ilzVtluMeiI3elZx07mxu7XQB9z4NILIbAW9bk0yaz3hO/tFbdpKT8k4p+kjMuYRprO7lw6jwfQvIvVSvR3jU05qSUAJ79UCBAjYX3fmzg4QWcqUygCjl/erofBJOMbkP2z5wmHdwlT4LgAQLpg5//PqLxiRYIXP+g417MRC52ZHUCKimRQdv+IWeVyaJbMTRaGsjM3/VGuAUh01fay+8XS3+7GKmK+kfevP8RFNyRLS+tfhQch4oXkeL9+uzfGS3nhLO/1ZrX3WFE3OTM63Ejh6A/yU2djByHzx9UH6/Ad2+DTbeA7UF96nlBtFyStuwWNuWeACWojb9+3RzxRayuJrVzXFTCC29/48m4AMOR8AK4s=
